import 'package:flutter/material.dart';
List festlist=[
  {
    'Festival' : 'Diwali',
    'word': 'Create your Diwali Templates',
    'Image' : 'assets/Diwali/img_2.1.jpg',
    'Color' : Colors.redAccent,
    'images':[
      'assets/Diwali/img_2.1.jpg',
      'assets/Diwali/img_2.2.jpg',
      'assets/Diwali/img_2.3.jpg',
      'assets/Diwali/img_2.4.jpg',
      'assets/Diwali/img_2.5.jpg',
    ],
  },
  {
    'Festival' : 'Pongal',
    'word': 'Create your Pongal Templates',
    'Image' : 'assets/Diwali/img_2.1.jpg',
    'Color' : Colors.purple,
    'images':[
      'assets/Diwali/img_2.1.jpg',
      'assets/Diwali/img_2.2.jpg',
      'assets/Diwali/img_2.3.jpg',
      'assets/Diwali/img_2.4.jpg',
      'assets/Diwali/img_2.5.jpg',
      'assets/Diwali/img_2.5.jpg',
    ],
  },
  {
    'Festival' : 'Raksha Bandhan',
    'word': 'Create your Raksha Bandhan Templates',
    'Image' : 'assets/raksha_bandhan/img_3.1.jpg',
    'Color' : Colors.yellow,
    'images':[
      'asset/img/festival_img/Raksha Bandhan/raksha_bandhan.jpg',
      'asset/img/festival_img/Raksha Bandhan/img1.jpg',
      'asset/img/festival_img/Raksha Bandhan/img2.jpg',
      'asset/img/festival_img/Raksha Bandhan/img3.jpg',
      'asset/img/festival_img/Raksha Bandhan/img4.jpg',
      'asset/img/festival_img/Raksha Bandhan/img5.jpg',
    ],
  },
  {
    'Festival' : 'Makar Sakranti',
    'word': 'Create your Makar Sakranti Templates',
    'Image' : 'assets/maker_sankrti/img_4.1_cleanup.jpg',
    'Color' :Colors.red,
    'images':[
      'assets/maker_sankrti/img_4.1_cleanup.jpg',
      'assets/maker_sankrti/img_4.2_cleanup.jpg',
      'assets/maker_sankrti/img_4.3_cleanup.jpg',
      'assets/maker_sankrti/img_4.4.jpg',
      'assets/maker_sankrti/img_4.5.jpg',
    ],
  },
  {
    'Festival' : 'Basant Panchami',
    'word': 'Create your Basant Panchami Templates',
    'Image' : 'assets/Diwali/img_2.1.jpg',
    'Color' : Colors.blue,
    'images':[
      'assets/Diwali/img_2.1.jpg',
      'assets/Diwali/img_2.2.jpg',
      'assets/Diwali/img_2.3.jpg',
      'assets/Diwali/img_2.4.jpg',
      'assets/Diwali/img_2.5.jpg',
    ],
  },
  {
    'Festival' : 'Maha Shivratri',
    'word': 'Create your Maha Shivratri Templates',
    'Image' :  'assets/Diwali/img_2.1.jpg',
    'Color' : Colors.brown,
    'images':[
      'assets/Diwali/img_2.1.jpg',
      'assets/Diwali/img_2.2.jpg',
      'assets/Diwali/img_2.3.jpg',
      'assets/Diwali/img_2.4.jpg',
      'assets/Diwali/img_2.5.jpg',
    ],
  },
  {
    'Festival' : 'Holi',
    'word': 'Create your holi Templates',
    'Image' : 'assets/holi/img_5.1.jpg',
    'Color' : Colors.lightGreen,
    'images':[
      'assets/holi/img_5.1.jpg',
      'assets/holi/img_5.2.jpg',
      'assets/holi/img_5.3.jpg',
      'assets/holi/img_5.4.jpg',
      'assets/holi/img_5.5.jpg',
    ],
  },
  {
    'Festival' : 'Navratri',
    'word': 'Create your Navratri Templates',
    'Image' : 'assets/Diwali/img_2.1.jpg',
    'Color' : Colors.red,
    'images':[
      'assets/Diwali/img_2.1.jpg',
      'assets/Diwali/img_2.2.jpg',
      'assets/Diwali/img_2.3.jpg',
      'assets/Diwali/img_2.4.jpg',
      'assets/Diwali/img_2.5.jpg',
    ],
  },
  {
    'Festival' : 'Bhai dhuj',
    'word': 'Create your Bhai dhuj Templates',
    'Image' :'assets/Diwali/img_2.1.jpg',
    'Color' : Colors.pink,
    'images':[
      'assets/Diwali/img_2.1.jpg',
      'assets/Diwali/img_2.2.jpg',
      'assets/Diwali/img_2.3.jpg',
      'assets/Diwali/img_2.4.jpg',
      'assets/Diwali/img_2.5.jpg',
    ],
  },
  {
    'Festival' : 'Ganesh Chaturthi',
    'word': 'Create your Ganesh Chaturthi Templates',
    'Image' : 'assets/genesh_chaturtiy/img_1.1.png',
    'Color' : Colors.deepOrange,
    'images':[
      'assets/genesh_chaturtiy/img_1.1.png',
      'assets/genesh_chaturtiy/img_1.2.png',
      'assets/genesh_chaturtiy/img_1.3.png',
      'assets/genesh_chaturtiy/img_1.4.png',
      'assets/genesh_chaturtiy/img_1.5.png',
    ],
  },
  {
    'Festival' : 'Independence Day',
    'word': 'Create your Independence Day Templates',
    'Image' : 'assets/genesh_chaturtiy/img_1.1.png',
    'Color' : Colors.orangeAccent,
    'images':[
      'assets/genesh_chaturtiy/img_1.1.png',
      'assets/genesh_chaturtiy/img_1.2.png',
      'assets/genesh_chaturtiy/img_1.3.png',
      'assets/genesh_chaturtiy/img_1.4.png',
      'assets/genesh_chaturtiy/img_1.5.png',
    ],
  },
  {
    'Festival' : 'Republic Day',
    'word': 'Create your Republic Day Templates',
    'Image' :  'assets/genesh_chaturtiy/img_1.1.png',
    'Color' : Colors.black54,
    'images':[
      'assets/genesh_chaturtiy/img_1.1.png',
      'assets/genesh_chaturtiy/img_1.2.png',
      'assets/genesh_chaturtiy/img_1.3.png',
      'assets/genesh_chaturtiy/img_1.4.png',
      'assets/genesh_chaturtiy/img_1.5.png',
    ],
  },

];